### ISSUE TITLE
the dataset is not accessed

### ISSUE THREAD

**Issue by xiaoxiaoSummer** [SwissDataScienceCenter/DeepSphere#25]
The dataset 

July 4, 2018 Dataset Closed Access
Convergence maps dataset

Nathanaël Perraudin; Michaël Defferrard; Tomasz Kacprzak; Raphael Sgier

This dataset is composed of 60 spherical convergence maps (30 per class), separated into a training set of 40 maps and a testing set of 20 maps.

As a preprocessing, we recommend to remove the mean of each map and to smooth them with a Gaussian symmetric beam of 3 arcmins (sphtfunc.smoothing in Healpy).

This dataset is used in "HealpixNet: Efficient spherical Convolutional Neural Network with Healpix sampling for cosmological applications"

Files
Closed Access

Files are not publicly accessible.

So how to fix this?

**Comment by mdeff** [comment]
The dataset is indeed not publicly available. As mentioned in the [README](https://github.com/SwissDataScienceCenter/DeepSphere#reproducing-the-results-of-the-paper), that is the private data you need to ask a copy for.

**Comment by nperraud** [comment]
Sorry for the delay with the access. There is now an option on Zenodo to request access for the dataset at https://zenodo.org/record/1303272

It requires writing a description of the project which the dataset is intended to be used.
