### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/same_psd/smoothed_class1_sigma3.npz'

### ISSUE THREAD

**Issue by jiapei100** [SwissDataScienceCenter/DeepSphere#27]
FileNotFoundError: [Errno 2] No such file or directory: 'data/same_psd/smoothed_class1_sigma3.npz'

**Comment by mdeff** [comment]
As mentioned in the [README](https://github.com/SwissDataScienceCenter/DeepSphere#reproducing-the-results-of-the-paper), that is the private data you need to ask a copy for.

Where did the error come from? Should we have an explicit error message?
