### ISSUE TITLE
Multiple channel

### ISSUE THREAD

**Issue by nperraud** [SwissDataScienceCenter/DeepSphere#29]
Deepsphere is not working with multiple channels.

**Comment by nperraud** [comment]
I just created a branch to handle multiple channels:

https://github.com/SwissDataScienceCenter/DeepSphere/tree/multichannel

**Comment by acagansengul** [comment]
Could you please upload an example code that uses the multiple channels feature.

**Comment by nperraud** [comment]
Here is a link to download an example notebook

https://we.tl/t-dE4thlipQt

**Comment by mdeff** [comment]
Shall we include that in the repo?

**Comment by nperraud** [comment]
What I provide with the link, for sure not. I just copy the data on all the channels. It is just an example for how to use it. If we found some data, then it would be good. Would be good to have some regression task as well.

**Comment by mdeff** [comment]
I think we should have an example notebook with many tasks (1 / multiple input maps, global / dense prediction, classification / regression). We probably don't need real data / task for that. It's just meant to be an usage guide.

**Comment by nperraud** [comment]
Then this is linked to this issue
https://github.com/SwissDataScienceCenter/DeepSphere/issues/30

**Comment by acagansengul** [comment]
Thank you, it seems to be working for me.

**Comment by nperraud** [comment]
This has been implemented in the branch multichannel. There is a demo notebook here:
https://github.com/SwissDataScienceCenter/DeepSphere/blob/multichannel/demo_regression.ipynb
