### ISSUE TITLE
Running DeepSphere for regression?

### ISSUE THREAD

**Issue by acagansengul** [SwissDataScienceCenter/DeepSphere#30]
Is there a version of DeepSphere that can run regression instead of classification?

**Comment by nperraud** [comment]
Unfortunately, the loss used right now is for classification only. However, changing the loss should be  simple. We can help you to do this. What loss do you want to use?

**Comment by acagansengul** [comment]
Thank you. I want to use mean_squared_error.

**Comment by nperraud** [comment]
As I am quite busy, I will not have the time to implement this before the 23. So if you need this very soon, you will have to implement it yourself.

**Comment by nperraud** [comment]
I just implemented the l2 and l1 losses for regression in the multichannel branch... 
https://github.com/SwissDataScienceCenter/DeepSphere/tree/multichannel
There is a notebook demo_regression.
https://github.com/SwissDataScienceCenter/DeepSphere/blob/multichannel/demo_regression.ipynb
Please test and let us know if you encounter any issue with the code.

**Comment by mdeff** [comment]
Support for regression and multiple channels has been implemented in #31 (thanks @nperraud). Feel free to reopen or create another issue if needed.
